#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0x01380DF54FD09D02 (frlan@fsfe.org)
#
Name     : geany-plugins
Version  : 2.0
Release  : 29
URL      : https://plugins.geany.org/geany-plugins/geany-plugins-2.0.tar.gz
Source0  : https://plugins.geany.org/geany-plugins/geany-plugins-2.0.tar.gz
Source1  : https://plugins.geany.org/geany-plugins/geany-plugins-2.0.tar.gz.sig
Source2  : 01380DF54FD09D02.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 GPL-3.0
BuildRequires : buildreq-configure
BuildRequires : check-dev
BuildRequires : cppcheck
BuildRequires : enchant-dev
BuildRequires : file
BuildRequires : glib-dev
BuildRequires : gnupg
BuildRequires : gpgme-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : itstool
BuildRequires : libassuan-dev
BuildRequires : libgit2-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(enchant)
BuildRequires : pkgconfig(geany)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtkspell3-3.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : vte-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
===============
Geany-Plugins
===============
Installation
------------
You can build the plugins using Autotools.

%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 01380DF54FD09D02' gpg.status
%setup -q -n geany-plugins-2.0
cd %{_builddir}/geany-plugins-2.0
pushd ..
cp -a geany-plugins-2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713291207
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1713291207
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/geany-plugins
cp %{_builddir}/geany-plugins-%{version}/addons/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/autoclose/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/automark/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/codenav/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/commander/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/debugger/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/defineformat/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/geanyctags/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geanydoc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/geanyextrasel/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geanygendoc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/geanyinsertnum/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geanylua/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/geanymacro/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geanyminiscript/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/geanynumberedbookmarks/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geanypg/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/geany-plugins-%{version}/geanyprj/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/geanyvc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/geniuspaste/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/bb10dfa63153009c4cdfd449264e19050891d3da || :
cp %{_builddir}/geany-plugins-%{version}/git-changebar/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/keyrecord/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/latex/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/lineoperations/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/lipsum/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/markdown/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/geany-plugins-%{version}/pairtaghighlighter/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/104f0ca2787c6fb7ab82cc22998b0f223aaa1e37 || :
cp %{_builddir}/geany-plugins-%{version}/pohelper/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/pretty-printer/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/projectorganizer/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/scope/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/sendmail/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/shiftcolumn/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/geany-plugins-%{version}/spellcheck/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/tableconvert/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/fa67bad6ceae56388058e04f8b4979eb8c964526 || :
cp %{_builddir}/geany-plugins-%{version}/updatechecker/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
cp %{_builddir}/geany-plugins-%{version}/utils/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/vimode/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/webhelper/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/geany-plugins-%{version}/workbench/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/909b58c9b803acb8d063ac6b2147e56afc8055f6 || :
cp %{_builddir}/geany-plugins-%{version}/xmlsnippets/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/4d1d37f306ed270cda5b2741fac3abf0a7b012e5 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
