#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : geany-plugins
Version  : 1.33.0
Release  : 6
URL      : https://github.com/geany/geany-plugins/archive/1.33.0.tar.gz
Source0  : https://github.com/geany/geany-plugins/archive/1.33.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 GPL-3.0 MIT
Requires: geany-plugins-data = %{version}-%{release}
Requires: geany-plugins-lib = %{version}-%{release}
Requires: geany-plugins-license = %{version}-%{release}
Requires: geany-plugins-locales = %{version}-%{release}
BuildRequires : enchant-dev
BuildRequires : glib-dev
BuildRequires : gpgme-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : itstool
BuildRequires : libassuan-dev
BuildRequires : libgit2-dev
BuildRequires : libgpg-error-dev
BuildRequires : libsoup-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(enchant)
BuildRequires : pkgconfig(geany)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtkspell3-3.0)
BuildRequires : vte-dev
BuildRequires : zlib-dev

%description
===============
Geany-Plugins
===============
Status
------
.. image:: https://travis-ci.org/geany/geany-plugins.svg?branch=master
:target: https://travis-ci.org/geany/geany-plugins

%package data
Summary: data components for the geany-plugins package.
Group: Data

%description data
data components for the geany-plugins package.


%package dev
Summary: dev components for the geany-plugins package.
Group: Development
Requires: geany-plugins-lib = %{version}-%{release}
Requires: geany-plugins-data = %{version}-%{release}
Provides: geany-plugins-devel = %{version}-%{release}

%description dev
dev components for the geany-plugins package.


%package doc
Summary: doc components for the geany-plugins package.
Group: Documentation

%description doc
doc components for the geany-plugins package.


%package lib
Summary: lib components for the geany-plugins package.
Group: Libraries
Requires: geany-plugins-data = %{version}-%{release}
Requires: geany-plugins-license = %{version}-%{release}

%description lib
lib components for the geany-plugins package.


%package license
Summary: license components for the geany-plugins package.
Group: Default

%description license
license components for the geany-plugins package.


%package locales
Summary: locales components for the geany-plugins package.
Group: Default

%description locales
locales components for the geany-plugins package.


%prep
%setup -q -n geany-plugins-1.33.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543327427
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1543327427
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/geany-plugins
cp addons/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/addons_COPYING
cp autoclose/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/autoclose_COPYING
cp automark/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/automark_COPYING
cp codenav/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/codenav_COPYING
cp commander/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/commander_COPYING
cp debugger/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/debugger_COPYING
cp defineformat/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/defineformat_COPYING
cp devhelp/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/devhelp_COPYING
cp geanyctags/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyctags_COPYING
cp geanydoc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanydoc_COPYING
cp geanyextrasel/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyextrasel_COPYING
cp geanygendoc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanygendoc_COPYING
cp geanyinsertnum/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyinsertnum_COPYING
cp geanylua/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanylua_COPYING
cp geanymacro/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanymacro_COPYING
cp geanyminiscript/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyminiscript_COPYING
cp geanynumberedbookmarks/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanynumberedbookmarks_COPYING
cp geanypg/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanypg_COPYING
cp geanyprj/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyprj_COPYING
cp geanypy/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanypy_COPYING
cp geanyvc/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geanyvc_COPYING
cp geniuspaste/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/geniuspaste_COPYING
cp git-changebar/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/git-changebar_COPYING
cp keyrecord/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/keyrecord_COPYING
cp latex/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/latex_COPYING
cp lineoperations/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/lineoperations_COPYING
cp lipsum/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/lipsum_COPYING
cp markdown/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/markdown_COPYING
cp markdown/peg-markdown/LICENSE %{buildroot}/usr/share/package-licenses/geany-plugins/markdown_peg-markdown_LICENSE
cp multiterm/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/multiterm_COPYING
cp pairtaghighlighter/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/pairtaghighlighter_COPYING
cp pohelper/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/pohelper_COPYING
cp pretty-printer/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/pretty-printer_COPYING
cp projectorganizer/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/projectorganizer_COPYING
cp scope/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/scope_COPYING
cp sendmail/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/sendmail_COPYING
cp shiftcolumn/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/shiftcolumn_COPYING
cp spellcheck/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/spellcheck_COPYING
cp tableconvert/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/tableconvert_COPYING
cp updatechecker/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/updatechecker_COPYING
cp utils/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/utils_COPYING
cp webhelper/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/webhelper_COPYING
cp workbench/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/workbench_COPYING
cp xmlsnippets/COPYING %{buildroot}/usr/share/package-licenses/geany-plugins/xmlsnippets_COPYING
%make_install
%find_lang geany-plugins

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/geany-plugins/geniuspaste/pastebins/codepad.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/dpaste.de.conf
/usr/share/geany-plugins/geniuspaste/pastebins/fpaste.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/paste.debian.net.conf
/usr/share/geany-plugins/geniuspaste/pastebins/pastebin.geany.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/sprunge.us.conf
/usr/share/geany-plugins/git-changebar/prefs.ui
/usr/share/geany-plugins/overview/prefs.ui
/usr/share/geany-plugins/pohelper/menus.ui
/usr/share/geany-plugins/pohelper/stats.ui

%files dev
%defattr(-,root,root,-)
/usr/lib64/libgeanypluginutils.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/geany\-plugins/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/geany/addons.so
/usr/lib64/geany/autoclose.so
/usr/lib64/geany/automark.so
/usr/lib64/geany/codenav.so
/usr/lib64/geany/commander.so
/usr/lib64/geany/defineformat.so
/usr/lib64/geany/geanyctags.so
/usr/lib64/geany/geanydoc.so
/usr/lib64/geany/geanyextrasel.so
/usr/lib64/geany/geanyinsertnum.so
/usr/lib64/geany/geanymacro.so
/usr/lib64/geany/geanyminiscript.so
/usr/lib64/geany/geanynumberedbookmarks.so
/usr/lib64/geany/geanypg.so
/usr/lib64/geany/geanyprj.so
/usr/lib64/geany/geanyvc.so
/usr/lib64/geany/geniuspaste.so
/usr/lib64/geany/git-changebar.so
/usr/lib64/geany/keyrecord.so
/usr/lib64/geany/latex.so
/usr/lib64/geany/lineoperations.so
/usr/lib64/geany/lipsum.so
/usr/lib64/geany/overview.so
/usr/lib64/geany/pairtaghighlighter.so
/usr/lib64/geany/pohelper.so
/usr/lib64/geany/pretty-printer.so
/usr/lib64/geany/projectorganizer.so
/usr/lib64/geany/sendmail.so
/usr/lib64/geany/shiftcolumn.so
/usr/lib64/geany/spellcheck.so
/usr/lib64/geany/tableconvert.so
/usr/lib64/geany/treebrowser.so
/usr/lib64/geany/updatechecker.so
/usr/lib64/geany/workbench.so
/usr/lib64/geany/xmlsnippets.so
/usr/lib64/libgeanypluginutils.so.0
/usr/lib64/libgeanypluginutils.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/geany-plugins/addons_COPYING
/usr/share/package-licenses/geany-plugins/autoclose_COPYING
/usr/share/package-licenses/geany-plugins/automark_COPYING
/usr/share/package-licenses/geany-plugins/codenav_COPYING
/usr/share/package-licenses/geany-plugins/commander_COPYING
/usr/share/package-licenses/geany-plugins/debugger_COPYING
/usr/share/package-licenses/geany-plugins/defineformat_COPYING
/usr/share/package-licenses/geany-plugins/devhelp_COPYING
/usr/share/package-licenses/geany-plugins/geanyctags_COPYING
/usr/share/package-licenses/geany-plugins/geanydoc_COPYING
/usr/share/package-licenses/geany-plugins/geanyextrasel_COPYING
/usr/share/package-licenses/geany-plugins/geanygendoc_COPYING
/usr/share/package-licenses/geany-plugins/geanyinsertnum_COPYING
/usr/share/package-licenses/geany-plugins/geanylua_COPYING
/usr/share/package-licenses/geany-plugins/geanymacro_COPYING
/usr/share/package-licenses/geany-plugins/geanyminiscript_COPYING
/usr/share/package-licenses/geany-plugins/geanynumberedbookmarks_COPYING
/usr/share/package-licenses/geany-plugins/geanypg_COPYING
/usr/share/package-licenses/geany-plugins/geanyprj_COPYING
/usr/share/package-licenses/geany-plugins/geanypy_COPYING
/usr/share/package-licenses/geany-plugins/geanyvc_COPYING
/usr/share/package-licenses/geany-plugins/geniuspaste_COPYING
/usr/share/package-licenses/geany-plugins/git-changebar_COPYING
/usr/share/package-licenses/geany-plugins/keyrecord_COPYING
/usr/share/package-licenses/geany-plugins/latex_COPYING
/usr/share/package-licenses/geany-plugins/lineoperations_COPYING
/usr/share/package-licenses/geany-plugins/lipsum_COPYING
/usr/share/package-licenses/geany-plugins/markdown_COPYING
/usr/share/package-licenses/geany-plugins/markdown_peg-markdown_LICENSE
/usr/share/package-licenses/geany-plugins/multiterm_COPYING
/usr/share/package-licenses/geany-plugins/pairtaghighlighter_COPYING
/usr/share/package-licenses/geany-plugins/pohelper_COPYING
/usr/share/package-licenses/geany-plugins/pretty-printer_COPYING
/usr/share/package-licenses/geany-plugins/projectorganizer_COPYING
/usr/share/package-licenses/geany-plugins/scope_COPYING
/usr/share/package-licenses/geany-plugins/sendmail_COPYING
/usr/share/package-licenses/geany-plugins/shiftcolumn_COPYING
/usr/share/package-licenses/geany-plugins/spellcheck_COPYING
/usr/share/package-licenses/geany-plugins/tableconvert_COPYING
/usr/share/package-licenses/geany-plugins/updatechecker_COPYING
/usr/share/package-licenses/geany-plugins/utils_COPYING
/usr/share/package-licenses/geany-plugins/webhelper_COPYING
/usr/share/package-licenses/geany-plugins/workbench_COPYING
/usr/share/package-licenses/geany-plugins/xmlsnippets_COPYING

%files locales -f geany-plugins.lang
%defattr(-,root,root,-)

