#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : geany-plugins
Version  : 1.32.0
Release  : 2
URL      : https://github.com/geany/geany-plugins/archive/1.32.0.tar.gz
Source0  : https://github.com/geany/geany-plugins/archive/1.32.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 GPL-3.0 MIT
Requires: geany-plugins-lib
Requires: geany-plugins-doc
Requires: geany-plugins-data
Requires: geany-plugins-locales
BuildRequires : enchant-dev
BuildRequires : glib-dev
BuildRequires : gpgme-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : itstool
BuildRequires : libassuan-dev
BuildRequires : libgit2-dev
BuildRequires : libgpg-error-dev
BuildRequires : libsoup-dev
BuildRequires : libxml2-dev
BuildRequires : pkgconfig(geany)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : vte-dev
BuildRequires : zlib-dev

%description
===============
Geany-Plugins
===============
Status
------
.. image:: https://travis-ci.org/geany/geany-plugins.svg?branch=master
:target: https://travis-ci.org/geany/geany-plugins

%package data
Summary: data components for the geany-plugins package.
Group: Data

%description data
data components for the geany-plugins package.


%package dev
Summary: dev components for the geany-plugins package.
Group: Development
Requires: geany-plugins-lib
Requires: geany-plugins-data
Provides: geany-plugins-devel

%description dev
dev components for the geany-plugins package.


%package doc
Summary: doc components for the geany-plugins package.
Group: Documentation

%description doc
doc components for the geany-plugins package.


%package lib
Summary: lib components for the geany-plugins package.
Group: Libraries
Requires: geany-plugins-data

%description lib
lib components for the geany-plugins package.


%package locales
Summary: locales components for the geany-plugins package.
Group: Default

%description locales
locales components for the geany-plugins package.


%prep
%setup -q -n geany-plugins-1.32.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516720517
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516720517
rm -rf %{buildroot}
%make_install
%find_lang geany-plugins

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/geany-plugins/geniuspaste/pastebins/codepad.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/dpaste.de.conf
/usr/share/geany-plugins/geniuspaste/pastebins/fpaste.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/paste.debian.net.conf
/usr/share/geany-plugins/geniuspaste/pastebins/pastebin.geany.org.conf
/usr/share/geany-plugins/geniuspaste/pastebins/sprunge.us.conf
/usr/share/geany-plugins/git-changebar/prefs.ui
/usr/share/geany-plugins/overview/prefs.ui
/usr/share/geany-plugins/pohelper/menus.ui
/usr/share/geany-plugins/pohelper/stats.ui

%files dev
%defattr(-,root,root,-)
/usr/lib64/libgeanypluginutils.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/geany\-plugins/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/geany/addons.so
/usr/lib64/geany/autoclose.so
/usr/lib64/geany/automark.so
/usr/lib64/geany/codenav.so
/usr/lib64/geany/commander.so
/usr/lib64/geany/defineformat.so
/usr/lib64/geany/geanyctags.so
/usr/lib64/geany/geanydoc.so
/usr/lib64/geany/geanyextrasel.so
/usr/lib64/geany/geanyinsertnum.so
/usr/lib64/geany/geanylatex.so
/usr/lib64/geany/geanymacro.so
/usr/lib64/geany/geanyminiscript.so
/usr/lib64/geany/geanynumberedbookmarks.so
/usr/lib64/geany/geanypg.so
/usr/lib64/geany/geanyprj.so
/usr/lib64/geany/geanyvc.so
/usr/lib64/geany/geniuspaste.so
/usr/lib64/geany/git-changebar.so
/usr/lib64/geany/keyrecord.so
/usr/lib64/geany/lineoperations.so
/usr/lib64/geany/lipsum.so
/usr/lib64/geany/overview.so
/usr/lib64/geany/pairtaghighlighter.so
/usr/lib64/geany/pohelper.so
/usr/lib64/geany/pretty-printer.so
/usr/lib64/geany/projectorganizer.so
/usr/lib64/geany/sendmail.so
/usr/lib64/geany/shiftcolumn.so
/usr/lib64/geany/spellcheck.so
/usr/lib64/geany/tableconvert.so
/usr/lib64/geany/treebrowser.so
/usr/lib64/geany/updatechecker.so
/usr/lib64/geany/workbench.so
/usr/lib64/geany/xmlsnippets.so
/usr/lib64/libgeanypluginutils.so.0
/usr/lib64/libgeanypluginutils.so.0.0.0

%files locales -f geany-plugins.lang
%defattr(-,root,root,-)

